### PR TITLE
Peridot doctrine plugin - initial implementation

### PR DESCRIPTION
**Pull request by mrkrstphr**

### CODE REVIEW

**Comment by austinsmorris** [comment]
See #2.  If that's cool, let's close this and build from there.

**Comment by austinsmorris** [comment]
@mrkrstphr, @brianium, check it out....

**Comment by mrkrstphr** [comment]
Installing this in my test project right now. I'll play around with it.

**Comment by austinsmorris** [comment]
ok, cool

**Comment by mrkrstphr** [comment]
@brianium do you want a look at this? otherwise, I'm good with it. Needs some more convenience methods, but it's a good start.

**Pull request merged**
